INSERT INTO influencers (name, ig_handle, followers, brand, date_posted) VALUES ('Jen Reed', 'thesisterstudioig', 706000, 'Target', '2020-01-01');
INSERT INTO influencers (name, ig_handle, followers, brand, date_posted) VALUES ('Courtney Shields', 'courtney_shields', 577000, 'Target', '2020-01-01');
INSERT INTO influencers (name, ig_handle, followers, brand, date_posted) VALUES ('Amy Jackson', 'fashion_jackson', 555000, 'Target', '2020-01-01');
INSERT INTO influencers (name, ig_handle, followers, brand, date_posted) VALUES ('Julia Marcum', 'chrislovesjulia', 346000, 'Target', '2020-01-01');
INSERT INTO influencers (name, ig_handle, followers, brand, date_posted) VALUES ('Sandi + Shalia', 'thespoiledhome', 321000, 'Target', '2020-01-01');
INSERT INTO influencers (name, ig_handle, followers, brand, date_posted) VALUES ('Brooke + Meggan', 'somewherelatley', 266000, 'Target', '2020-01-01');
INSERT INTO influencers (name, ig_handle, followers, brand, date_posted) VALUES ('Liz Joy', 'purejoyhome', 207000, 'Target', '2020-01-01');
INSERT INTO influencers (name, ig_handle, followers, brand, date_posted) VALUES ('Liz Adams', 'lizadams', 153000, 'Target', '2020-01-01');
INSERT INTO influencers (name, ig_handle, followers, brand, date_posted) VALUES ('Katie Staples', 'halfway_wholeistic', 138000, 'Target', '2020-01-01');
INSERT INTO influencers (name, ig_handle, followers, brand, date_posted) VALUES ('Lisa Allen', 'lisa_allen', 110000, 'Target', '2020-01-01');
INSERT INTO influencers (name, ig_handle, followers, brand, date_posted) VALUES ('Kelly Larkin', 'kellyinthecity', 95200, 'Target', '2020-01-01');