INSERT INTO influencers (name, ig_handle, followers, brand, date_posted) VALUES ('Jen Reed', 'thesisterstudioig', 706000, 'Express', '2019-11-30');
INSERT INTO influencers (name, ig_handle, followers, brand, date_posted) VALUES ('Amber Fillerup Clark', 'amberfillerup', 14000000, "Land's End", '2019-12-06');
INSERT INTO influencers (name, ig_handle, followers, brand, date_posted) VALUES ('Amy Jackson', 'fashion_jackson', 555000, 'eBay', '2019-12-01');
INSERT INTO influencers (name, ig_handle, followers, brand, date_posted) VALUES ('Julia Marcum', 'chrislovesjulia', 346000, 'eBay', '2019-11-30');
INSERT INTO influencers (name, ig_handle, followers, brand, date_posted) VALUES ('Sandi + Shalia', 'thespoiledhome', 321000, 'Target', '2019-11-30');
INSERT INTO influencers (name, ig_handle, followers, brand, date_posted) VALUES ('Brooke + Meggan', 'somewherelatley', 266000, 'Express', '2019-11-29');
INSERT INTO influencers (name, ig_handle, followers, brand, date_posted) VALUES ('Mary Orton', 'maryorton', 228000, 'Nordstrom', '2019-11-25');
INSERT INTO influencers (name, ig_handle, followers, brand, date_posted) VALUES ('Liz Adams', 'lizadams', 153000, 'Nordstrom', '2019-11-25');
INSERT INTO influencers (name, ig_handle, followers, brand, date_posted) VALUES ('Katie Staples', 'halfway_wholeistic', 138000, 'Walmart', '2019-11-26');
INSERT INTO influencers (name, ig_handle, followers, brand, date_posted) VALUES ('Lisa Allen', 'lisa_allen', 110000, 'Nordstrom', '2019-11-26');
INSERT INTO influencers (name, ig_handle, followers, brand, date_posted) VALUES ('Kelly Larkin', 'kellyinthecity', 95200, 'eBay', '2019-11-30');